### ISSUE TITLE
Age 2 Villager / NPC transport (Interdimensional Cage)

### ISSUE THREAD

**Issue by Thiana** [borg286/sevtech#1]
The abyssalcraft Interdimensional Cage will transport Villagers, Mobs and animals. The only thing it doesn't seem to allow transporting is horses. You have to charge it before use, similar to the abyssalcraft book. Just place it in a charging pedestal and wait a few minutes.

Each capture seems to use about 30 PE.

**Comment by borg286** [comment]
Can you make an edit in the appropriate age in this document https://docs.google.com/document/d/1HQGPm90MVyieiiEkTPyfXIDBAvSkOAAQOoicTzFpmt0/edit?usp=drivesdk
